apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc # referenced in pods
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: ebs-sc

