---
- name: installation of various packages
  hosts: all
  become: yes
  tasks:
    - name: installation of git
      yum:
        name: git
        state: present
    - name: installation of docker
      yum:
        name: docker
        state: present
    - name: start docker service
      service:
        name: docker  
        state: started
...
