apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar
spec:
  containers:
    - name: nginx
      image: nginx
      ports:  
        - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
    
    - name: log-tailer
      image: busybox
      command: ["sh", "-c"]
      args: ["tail -f /var/log/nginx/access.log"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
  
  volumes:
    - name: shared-logs  #name of the volume - named volume
      emptyDir: {}