apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
    - name: wait-init
      image: busybox
      command: ['sh', '-c', 'echo "Init started"; sleep 30; echo "Init done"']
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80